[package]
name = "copy-changes"
version = "0.1.2"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.8.0"
structopt = "0.3.15"
walkdir = "2.3.1"
